### ISSUE TITLE
Add features to HTTP app

### ISSUE THREAD

**Issue by frikky** [Shuffle/python-apps#143]
Make it possible to pass cookies, basic auth and more with the HTTP app.

Essentially evolve it into an all-encompassing HTTP app

**Comment by tristandostaler** [comment]
Related to this, right now the http app assumes basic auth is always needed, which is not the case. I would fix the app with:
```
auth = None
if username or password:
    auth = requests.auth.HTTPBasicAuth(username, password)
requests.get(url, headers=parsed_headers, auth=auth, verify=verify).text
```

**Comment by frikky** [comment]
> Related to this, right now the http app assumes basic auth is always needed, which is not the case. I would fix the app with:
> 
> ```
> auth = None
> if username or password:
>     auth = requests.auth.HTTPBasicAuth(username, password)
> requests.get(url, headers=parsed_headers, auth=auth, verify=verify).text
> ```

Hey! You're indeed right. @shalin24999 could you fix this for us? @tristandostaler's implementation should be right, but I'd recommend testing it with

**Comment by frikky** [comment]
Reference for adding extra fields: https://github.com/Shuffle/shuffle-shared/blob/1480c2fa9ffd6a921e9aaee3d4ca272b5c124902/codegen.go#L536

Also: To all requests, add the header with user agent "Shuffle Automation"

**Comment by frikky** [comment]
Should all be done in latest! Cloud updates happening soon.
