### ISSUE TITLE
Create SQL app for getting and setting data

### ISSUE THREAD

**Issue by frikky** [Shuffle/python-apps#196]
For testing:
- Set up a SQL db, e.g. Postgresql
- Connect to it with username, password, domain, port etc.
- Make sure we can set and get data 

Extra:
- Make it possible to parse JSON straight to SQL

**Comment by frikky** [comment]
Issue with PostgreSQL library in Docker container. Issue with Alpine

**Comment by wbnod** [comment]
FYI, an increasing number of databases support JSON as a native data type. 
https://orangematter.solarwinds.com/2017/02/10/json-support-in-postgresql-mysql-mongodb-and-sql-server/

**Comment by frikky** [comment]
@dhaval055 did you get this one up and running?
