### ISSUE TITLE
Hive - Custom Fields no longer works

### ISSUE THREAD

**Issue by chasx003** [Shuffle/python-apps#229]
After Pulling the most recent update for Apps, the Hive App no longer adds Custom Fields to Hive cases

In app
![image](https://user-images.githubusercontent.com/4624854/146682552-b8afbb8a-b4ac-4c45-baba-2e021824d1e3.png)

After execution  (showing now custom fields added to the case)

![image](https://user-images.githubusercontent.com/4624854/146682631-8b82722e-996a-4ab7-8021-691845bb5f53.png)

For the create case issue, I believe issues start around line 175

 https://github.com/Shuffle/python-apps/blob/db1a1ad056e5f872481ed22e83e3be53b2798614/thehive/1.1.3/src/app.py#L175

This code in the except block used to always run, and now will only trigger if there is an issue

**Comment by frikky** [comment]
@shalin24999 could you check this out? 

Thanks

**Comment by frikky** [comment]
@shalin24999 create a case with the custom field "unique-phish-id" (as seen in the original photo), and then try to update it via API, either in a new case OR in an updated case

Manage custom fields: https://docs.thehive-project.org/thehive/user-guides/administrators/custom-fields/

**Comment by chasx003** [comment]
what is the goal of this  try/catch?   I can confirm that without it, the app was working.  I think there is an indent issue

```
        try:
            custom_fields = json.loads(custom_fields) if custom_fields else {}
        except json.decoder.JSONDecodeError:
```


my guess is it is a check like the  tlp / severity 

```
        if tlp > 3 or tlp < 0:
            return f"TLP needs to be a number from 0-3, not {tlp}"
        if severity > 4 or severity < 1:
            return f"Severity needs to be a number from 1-4, not {severity}"
```

I haven't tested this exactly, but this is my assumption for a fix



```
        # Prepare the customfields
        customfields = CustomFieldHelper()
        try:
            custom_fields = json.loads(custom_fields) if custom_fields else {}
        except json.decoder.JSONDecodeError:
            return "Custom fields need to be valid json"
        for key, value in custom_fields.items():
            if type(value) == int:
                customfields.add_integer(key, value)
            elif type(value) == str:
                customfields.add_string(key, value)
            elif type(value) == bool:
                customfields.add_boolean(key, value)
            elif type(value) == float:
                customfields.add_float(key, value)
            else:
                print(
                    f'The value type "{value}" of the field {key} is not suported by the function.'
                )

```

**Comment by shalin24999** [comment]
@chasx003 You were right. Have updated the code.

**Comment by chasx003** [comment]
awesome!  FYI, the same code block is in the update_case function as well :)

**Comment by frikky** [comment]
Hey @chasx003! Is this sorted? 

Thanks @shalin24999! :)

**Comment by chasx003** [comment]
Looks like it! (I'm using a local version now, but, the changes are the same as what is working on mine)
