### ISSUE TITLE
Jira app and liquidpy

### ISSUE THREAD

**Issue by tristandostaler** [Shuffle/python-apps#253]
I am not sure why, but I can't use liquidpy in the body of the jira app.
Example payload working:
```
{
  "update": {},
  "fields": {
    "summary":"$exec.summary",
    "issuetype": {
      "id": "10002"
    },
    "project": {
      "key": "TEST"
    },
    "description": {
        "type": "doc",
        "version": 1,
        "content": [{
          "type": "paragraph",
          "content": [{
            "text": "$exec.content",
            "type": "text"
          }]
        }]
      }
  }
}
```

Example payload NOT working:
```
{
  "update": {},
  "fields": {
    "summary":"$exec.summary",
    "issuetype": {
      "id": "10002"
    },
    "project": {
      "key": "TEST"
    },
    "description": {
        "type": "doc",
        "version": 1,
        "content": [{
          "type": "paragraph",
          "content": [{
            "text": "{{ $exec.content | replace: "a","b" }}",
            "type": "text"
          }]
        }]
      }
  }
}
```

**Comment by frikky** [comment]
Hey! 

Please try to use single quotes for the replace. Wondering whether it's failing some string parsing here.

![image](https://user-images.githubusercontent.com/5719530/150404371-6212fe14-42d4-4e23-be48-859b518b92c8.png)

**Comment by frikky** [comment]
Ah, here's the fix we're looking for. Inside the string itself, it is required that the $exec.content is wrapped as a string, meaning it needs quotes around it. Doesn't matter if single or double.

```
{
  "update": {},
  "fields": {
    "summary":"$exec.summary",
    "issuetype": {
      "id": "10002"
    },
    "project": {
      "key": "TEST"
    },
    "description": {
        "type": "doc",
        "version": 1,
        "content": [{
          "type": "paragraph",
          "content": [{
            "text": "{{ "$exec.content" | replace: "a","b" }}",
            "type": "text"
          }]
        }]
      }
  }
}
```

**Comment by tristandostaler** [comment]
Ok, I'll give it a try!

**Comment by tristandostaler** [comment]
Hum I don't know what I am doing wrong but I don't think it works. I get a "There was an error parsing JSON. Check that your request body is valid."

**Comment by frikky** [comment]
> Hum I don't know what I am doing wrong but I don't think it works. I get a "There was an error parsing JSON. Check that your request body is valid."

Could you try sending that exact JSON through the "Repeat back to me" action? That would show us the actual output being sent to the Jira target :+1:

**Comment by tristandostaler** [comment]
I don't want to paste the result here because there are sensitive info, but when I run the exact same payload in repeat back to me, it works. But when I validate the json, I can see an error because of some "\n" which should be "\\\n" I think. I'll try to replace "\n" with "\\\n" see if it works

**Comment by tristandostaler** [comment]
Hume somehow when I pipe in replace for "replace: "\n","\\n"", other well escaped characters (like C:\\) become problematic (like C:\)

**Comment by tristandostaler** [comment]
This works:
```
"content": [{
            "text": "{{ "$exec.content" | replace: "\\","\\\\" | replace: "\n", "\\n" | replace: "\"", "\\\"" }}",
            "type": "text"
          }
```

**Comment by tristandostaler** [comment]
So besides the brain fuck, I guess we can close the issue :P

**Comment by frikky** [comment]
> This works:
> 
> ```
> "content": [{
>             "text": "{{ "$exec.content" | replace: "\\","\\\\" | replace: "\n", "\\n" | replace: "\"", "\\\"" }}",
>             "type": "text"
>           }
> ```

Hahah, nice workaround there. I'm re-opening this as a bug anyway though, as that

**Comment by tristandostaler** [comment]
Linked to this, I am calling a webhook to call a subflow (so I don't need to display my user's API key in the parameters) using the HTTP app, and when receiving, ' are transformed in ".
I can confirm that in repeat back to me, nothing is transformed, so I assume it goes out the HTTP app as ', but can't confirm this.
Not sure why I am receiving "

**Comment by tristandostaler** [comment]
Found it: https://github.com/Shuffle/python-apps/blob/master/http/1.1.0/src/app.py#L99

I think this is a bug!

**Comment by tristandostaler** [comment]
I'll log a nw bug for this as it's not related to jira or anything else in this thread

**Comment by frikky** [comment]
> Found it: https://github.com/Shuffle/python-apps/blob/master/http/1.1.0/src/app.py#L99
> 
> I think this is a bug!

Well that's dumb :D Could you make a pull request to fix it with the json parse/ast checks maybe?

**Comment by tristandostaler** [comment]
Sure!

**Comment by tristandostaler** [comment]
https://github.com/Shuffle/python-apps/pull/256

**Comment by frikky** [comment]
Closing as #256 is closed
