### ISSUE TITLE
Email app "errors with success" and exception when imap inbox search returns zero results

### ISSUE THREAD

**Issue by 00willo** [Shuffle/python-apps#271]
The Get emails imap action of the email app, was found to return this when the search conditions for the amount of unread emails was not met and therefore the return from the underlying imaplib.

```
Status SUCCESS

Result 
Error during email processing: list index out of range
```

I've done some inital manual testing and diving into the code. Based on the results message displayed, the success status is actually set to False in the except block of the get_emails_imap method where it's fetching the email inside a for loop based on an empty list (resulting in No unread emails in this case). Likely this would also (TBC) if an empty inbox was processed.  There's a couple of index referened in the code that it could be but I think it's the email.fetch call that's causing it with the inbox in the test I'm testing.

**Comment by frikky** [comment]
Hey! I think this one may have been fixed yesterday with the version 1.2.0 as we're testing it ourselves right now too

**Comment by 00willo** [comment]
Ah, yes, I see your commit (af502ecd640f25ccb4a35641328fed35a3220e77), which went into 1.2 of the app in the repo. Sorry, I didn't think to check that so soon.

I'll pull it down and give it a test as well.

**Comment by 00willo** [comment]
@frikky That looks to work for me now. I tested with empty inbox, inbox with less than amount of emails requests, inbox that didn't have any unread.

**Comment by 00willo** [comment]
Scratch that. Found another list index out of range.

Condition is only a single email in inbox as unread. Email app is requesting 5, with Unread is set to true.

So, the email then gets marked as read and rerunning, it's fine, returns an empty list.  Mark it as unread again, rerun execution, get index range error. So, it's repeatable. Mark the single email as unread again, and change the Amount from 5 to 1, save and execute.  Returns as expected, the single file attachement of the email.
