### ISSUE TITLE
Make it possible to mark email as read with IMAP

### ISSUE THREAD

**Issue by frikky** [Shuffle/python-apps#272]
Somehow make it possible to mark them as read directly: https://stackoverflow.com/questions/2251977/python-imap-and-gmail-mark-messages-as-seen

I think it's based on the imap email id, so we're now passing that back in emails from 1.2.0

**Comment by 00willo** [comment]
FYI, for the testing scenario that I was performing in #271. Everytime the process ran to get emails successfully it marked the email it processed as read when that action occured.

**Comment by wolf0x** [comment]
Strange, why my Imap read mails always failure? tried several imap provider, neither credentials nor app key.

**Comment by 00willo** [comment]
My provider connection response was
`* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.`

For me, as the provider is hosting multiple domains, username is my full email address, it doesn't appear to be picky on the foldername (I've see some clients want `INBOX` not `Inbox`). I did have to remember to set ssl verify as False, as I was using my domain for the hostname for this testing.  On one my email clients I verify the presented certificate on first connect and accept that.   Side note: adding trust for a known cert to accept for this specifc connection may be better than accepting anything that get's presented.

**Comment by frikky** [comment]
This works thanks to @shalin24999
