### ISSUE TITLE
duplicate parse_list methods in Tools class - shuffle-tools

### ISSUE THREAD

**Issue by 00willo** [Shuffle/python-apps#283]
During some debugging of another issue, I discovered a duplicate method:
```
    def parse_list(self, input_list):
    def parse_list(self, items, splitter="\n"):
```

```
    def parse_list(self, input_list):
        try:
            input_list = json.loads(input_list)
            if isinstance(input_list, list):
                input_list = ",".join(input_list)
            else:
                return json.dumps(input_list)
        except:
            pass

        input_list = input_list.replace(", ", ",", -1)
        return input_list
```

```
    def parse_list(self, items, splitter="\n"):
        if splitter == "":
            splitter = "\n"

        splititems = items.split(splitter)

        return str(splititems)
```
The second method is the one being used during code execution.

**Comment by 00willo** [comment]
I'm happy to fix this. I confirmed that the `api.yml` currently defines the second `parse_list`.

Just need confirmation that the first one isn't needed at all, and does not possibly need to be renamed.

**Comment by frikky** [comment]
I think renaming is the thing we're looking for here. I'm working on a 1.2.0 of shuffle tools and just fixed it in there.

**Comment by 00willo** [comment]
@frikky Looks like this issue can be closed.  I see you renamed 
`def parse_list(self, input_list):` 
to 
`def parse_list_internal(self, input_list):`
as part of v1.2.0 being added in 2d741ba5
