### ISSUE TITLE
custom app Dockerfile - frikky/shuffle:app_sdk still current WALKOFF image?

### ISSUE THREAD

**Issue by 0xValthir** [Shuffle/python-apps#341]
Working on creating a custom app for an on-prem Shuffle installation and was looking through the required files, including the Dockerfile. In it, I noticed that the app_sdk image used is `frikky/shuffle:app_sdk`, which seemed like maybe it was outdated, considering the move of most other things to be owned by the Shuffle org. In addition, it seems potentially outdated.

I poked around at the packages under frikky's account and compared them to what was under the Shuffle org.
- frikky
  - [shuffle-app_sdk](https://github.com/users/frikky/packages/container/package/shuffle-app_sdk) - Last published 3 months ago
  - [app_sdk](https://github.com/users/frikky/packages/container/package/Shuffle%2Fapp_sdk) - Last published over 2 years ago
- Shuffle
  - [shuffle-app_sdk](https://github.com/orgs/Shuffle/packages/container/package/shuffle-app_sdk) - Last published 9 days ago

If I'm understanding correctly the app_sdk image used for this hasn't be updated in over 2 years. Is that correct? What about the other images? I looked at a sampling of other apps in the shuffle_apps repo and noticed they largely all still use that app_sdk image.

**Comment by frikky** [comment]
> Working on creating a custom app for an on-prem Shuffle installation and was looking through the required files, including the Dockerfile. In it, I noticed that the app_sdk image used is `frikky/shuffle:app_sdk`, which seemed like maybe it was outdated, considering the move of most other things to be owned by the Shuffle org. In addition, it seems potentially outdated.
> 
> I poked around at the packages under frikky's account and compared them to what was under the Shuffle org.
> 
> * frikky
>   
>   * [shuffle-app_sdk](https://github.com/users/frikky/packages/container/package/shuffle-app_sdk) - Last published 3 months ago
>   * [app_sdk](https://github.com/users/frikky/packages/container/package/Shuffle%2Fapp_sdk) - Last published over 2 years ago
> * Shuffle
>   
>   * [shuffle-app_sdk](https://github.com/orgs/Shuffle/packages/container/package/shuffle-app_sdk) - Last published 9 days ago
> 
> If I'm understanding correctly the app_sdk image used for this hasn't be updated in over 2 years. Is that correct? What about the other images? I looked at a sampling of other apps in the shuffle_apps repo and noticed they largely all still use that app_sdk image.

Hey! The naming and walkoff references are all due to backwards compatibility. Below is the default one, but you may choose to use the latest one from ghcr.io/shuffle/shuffle:app_sdk as well - it's up to you. We're moving away from frikky/* as you mentioned, so it may be better to start from shuffle/shuffle going forward for you.


Original: https://hub.docker.com/layers/frikky/shuffle/app_sdk/images/sha256-74f412dac17ea1273dfc3d46b5afb0311b427a9e47f11981804d6adca70fc496?context=repo

**Comment by 0xValthir** [comment]
Oh! I think my mistake was going by the Github packages, not Docker hub. That makes sense. Thanks!
