### ISSUE TITLE
AWS apps without credential but EC2-ROLE

### ISSUE THREAD

**Issue by mesutgungor** [Shuffle/python-apps#342]
Currently all AWS APPS like AWS-S3 , AWS-WAF ... needs credentials to be input
But if one gives the ec2 server (where shuffle is installed), the role with necesseary permissions the apps will not need credentials to be entered. 
So if the apps are modified that will handle this case it will be great.

**Comment by mesutgungor** [comment]
Tested locally and it seems to work as it is expected now. 
Created a pull request [https://github.com/Shuffle/python-apps/pull/343](url)

**Comment by frikky** [comment]
Continuing conversation in the PR. Looks nice, thanks! :)
