### ISSUE TITLE
Fix logs in python results when running shuffle tools -> execute python

### ISSUE THREAD

**Issue by frikky** [Shuffle/python-apps#351]
In short: it sometimes contains information about the logs instead of the result

Piping STDOUT may have not been ideal

https://github.com/Shuffle/python-apps/blob/985e380d2a58d6d7291660385775dfa0e54f511d/shuffle-tools/1.2.0/src/app.py#L509

**Comment by 0x0elliot** [comment]
#352

**Comment by 0x0elliot** [comment]
hey! this has not been closed yet. you took care of this.
