### ISSUE TITLE
Wazuh + Shuffle Integration

### ISSUE THREAD

**Issue by IAMLED** [Shuffle/python-apps#372]
I've configured the custom files and osse file as required, however, when I restart wazuh manager I see the following error message.

wazuh-integratord: ERROR: Couldn't execute command (integrations /tmp/custom-shuffle-1708102476--1260146396.alert  https://myip:port/api/v1/hooks/webhook_94f98e01-002f-4dba-98c8-565b9e410d0a   > /dev/null 2>&1). Check file and permissions.

How do I resolve this?

**Comment by frikky** [comment]
> I've configured the custom files and osse file as required, however, when I restart wazuh manager I see the following error message.
> 
> wazuh-integratord: ERROR: Couldn't execute command (integrations /tmp/custom-shuffle-1708102476--1260146396.alert https://myip:port/api/v1/hooks/webhook_94f98e01-002f-4dba-98c8-565b9e410d0a > /dev/null 2>&1). Check file and permissions.
> 
> How do I resolve this?

Hey,

this is a bug on the wazuh side, not in Shuffle. Please reach out to them to get help.

**Usually it is one of these:**
- The integration file doesn't exist
- Permissions for the file is bad
